### ISSUE TITLE
Cannot run on SteamOS /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by

### ISSUE THREAD

**Issue by subsoap** [GameAnalytics/GA-SDK-DEFOLD#9]
Could you test on a SteamOS install? Might be annoying but it's required to support SteamOS for Linux builds

Related post on the forum https://forum.defold.com/t/native-extensions/4946/206?u=pkeod

**Comment by the1schwartz** [comment]
Ok I can try that. Can I build for SteamOS in Defold or how do I test for SteamOS? (Haven't tried to test for SteamOS before)

**Comment by subsoap** [comment]
You just do a regular Linux build. SteamOS is like a super stripped down version of Linux. It's the only Linux version that had any problems with GA by the way out of a lot of testing we have done.

**Comment by the1schwartz** [comment]
OK thanks. Sorry for first looking into this now. It looks like I might need to get rid of using std::string as Mathias Westerdahl suggests, so hopefully that works once I am done with that.

**Comment by subsoap** [comment]
Any chance of fixing this soon? We are releasing a game on Monday on Steam and can't check Linux support box because this is preventing us from saying it works on SteamOS. Only option we would have is to remove this extension from the project.

**Comment by the1schwartz** [comment]
Sorry I am currently on holiday and I will first be back on Tuesday in the office. I am currently trying to remove the use of std::string in the underlying C++ sdk to see if that will fix it, which is taking a bit longer than expected since some 3rd party code ( jsoncpp) used by the c++ and needs to be changed as well so I will be straight on it when I am back again but don't know how it will take to fix exactly depending on how smoothly the migration from std::string to c strings will go. Sorry for the inconvenience.

**Comment by the1schwartz** [comment]
Sorry about the waiting but I am still working on getting rid of std::string and I am almost done so crossing fingers that will solve the issue. Sorry again about the inconvenience.

**Comment by the1schwartz** [comment]
This should finally be fixed now and I have tested on SteamOS as well and it looks to work now!! Main change in the SDK was to switch from using JsonCpp library to use rapidjson library instead for our Json operations. Let me know if you still have issues or any other problems have arised after the update. This works in the lates version v2.2.1.
